[package]
name = "Advent_Of_Code_2020"
version = "0.1.0"
authors = ["Malachy Gilchrist <malachygilchrist@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
